<a href="https://colab.research.google.com/github/animeshdhakal/PyTorchBasics/blob/main/PyTorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

## Create a Empty Tensor
We can create a empty tensor with the corresponding size



In [2]:
torch.empty(3, 3, 3)

tensor([[[9.5205e-35, 0.0000e+00, 1.4293e-43],
         [0.0000e+00,        nan, 0.0000e+00],
         [1.1434e+27, 7.5555e+31, 1.2705e+31]],

        [[7.0948e+22, 3.8946e+21, 4.4650e+30],
         [1.1286e+27, 2.8405e+20, 3.2608e-12],
         [1.4583e-19, 1.0899e+27, 6.8943e+34]],

        [[1.1835e+22, 7.0976e+22, 5.7886e+22],
         [6.7120e+22, 1.1632e+33, 3.2598e-12],
         [7.4086e+28, 7.1463e+22, 4.6241e+30]]])

## Create a Tensor with random value


In [3]:
torch.rand(3, 3, 3)

tensor([[[0.8215, 0.9641, 0.2417],
         [0.2850, 0.5304, 0.3581],
         [0.5170, 0.9815, 0.3806]],

        [[0.7583, 0.2634, 0.6167],
         [0.6544, 0.5620, 0.5754],
         [0.6404, 0.9760, 0.3217]],

        [[0.5371, 0.1948, 0.7972],
         [0.0034, 0.1431, 0.0346],
         [0.0442, 0.7760, 0.3024]]])

## Create a Tensor with all values one

In [4]:
torch.ones(1, 2)

tensor([[1., 1.]])

## Get the Datatype of Tensor

In [5]:
x = torch.rand(1, 2)
x.dtype

torch.float32

## Change Datatype of Tensor

In [6]:
x = torch.rand(1, 2, dtype=torch.float64)
x.dtype

torch.float64

## Get the size of Tensor

In [7]:
x.shape

torch.Size([1, 2])

## Arithmetic Operations

In [8]:
x = torch.tensor([1, 2])
y = torch.tensor([2, 4])

In [9]:
torch.mul(x, y)

tensor([2, 8])

In [10]:
x.mul_(y) # This is inplace operation which will assign result to x variable
x

tensor([2, 8])

## Slicing Tensor

In [11]:
x = torch.rand(2, 2)

In [12]:
x

tensor([[0.2648, 0.4273],
        [0.1020, 0.9590]])

In [13]:
x[:, 1]

tensor([0.4273, 0.9590])

In [14]:
x[1, :]

tensor([0.1020, 0.9590])

## Reshaping Tensor

In [15]:
x = torch.rand(3, 4)

In [16]:
x

tensor([[0.2842, 0.8096, 0.7968, 0.0151],
        [0.8443, 0.3252, 0.1726, 0.3200],
        [0.1981, 0.3476, 0.6774, 0.4290]])

In [17]:
x.reshape(12)

tensor([0.2842, 0.8096, 0.7968, 0.0151, 0.8443, 0.3252, 0.1726, 0.3200, 0.1981,
        0.3476, 0.6774, 0.4290])

In [18]:
x.reshape(2, 6)

tensor([[0.2842, 0.8096, 0.7968, 0.0151, 0.8443, 0.3252],
        [0.1726, 0.3200, 0.1981, 0.3476, 0.6774, 0.4290]])

## Numpy to Tensor and Vice Versa
Here both shares same memory

In [19]:
x = torch.rand(3, 3)

In [20]:
y = x.numpy()

In [21]:
x

tensor([[0.6041, 0.4942, 0.5477],
        [0.7990, 0.9834, 0.5860],
        [0.2733, 0.6204, 0.2637]])

In [22]:
y

array([[0.60406566, 0.49417466, 0.5477161 ],
       [0.7989809 , 0.98337793, 0.5860391 ],
       [0.2732569 , 0.6203838 , 0.26370674]], dtype=float32)

In [23]:
x[1, 1] = 2

In [24]:
x

tensor([[0.6041, 0.4942, 0.5477],
        [0.7990, 2.0000, 0.5860],
        [0.2733, 0.6204, 0.2637]])

In [25]:
y

array([[0.60406566, 0.49417466, 0.5477161 ],
       [0.7989809 , 2.        , 0.5860391 ],
       [0.2732569 , 0.6203838 , 0.26370674]], dtype=float32)

In [26]:
x = np.array([1, 2, 3])

In [27]:
y = torch.from_numpy(x)

In [28]:
y

tensor([1, 2, 3])

## Using GPU

In [29]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [32]:
x = torch.rand([1, 2], device=device)

In [33]:
# Convert Previous Tensor to GPU
y = torch.rand([1, 2])

In [34]:
y = y.to(device)

In [35]:
y.device

device(type='cuda', index=0)

## Autograd

In [71]:
a = torch.randn(3, requires_grad=True)

In [72]:
a

tensor([-0.2629,  0.9816,  0.5537], requires_grad=True)

In [73]:
b = a.mean()

In [74]:
b.backward() # dy / dx

In [77]:
a

tensor([-0.2629,  0.9816,  0.5537], requires_grad=True)

In [80]:
with torch.no_grad(): # Stop Creating Gradient Function
  b = a * 2

In [81]:
b

tensor([-0.5259,  1.9632,  1.1074])